# https://projecteuler.net/problem=2
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
# Expected value: 4613732
from shared import fib
from itertools import filterfalse, takewhile
print(sum(filterfalse(lambda y:y%2==0, takewhile(lambda x: x < 4000000, fib()))))